-- Schema reconciliation migration generated from Supabase exports (columns, FKs, and RLS)
-- and aligned with current app query usage.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Core tables from provided schema snapshot
-- ---------------------------------------------------------------------------

create table if not exists public.landlords (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  stripe_account_id text,
  stripe_customer_id text,
  stripe_subscription_id text,
  subscription_status text,
  subscription_current_period_end timestamptz,
  user_id uuid not null default auth.uid(),
  stripe_connect_account_id text,
  stripe_connect_onboarded boolean default false,
  trial_active boolean not null default false,
  trial_end date,
  subscription_active boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.landlord_team_members (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null,
  member_email text,
  member_user_id uuid,
  role text not null default 'member'::text,
  invited_at timestamptz not null default now(),
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  invite_email text,
  status text default 'pending'::text,
  owner_landlord_id bigint
);

create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  owner_id uuid not null,
  property_id bigint,
  title text not null,
  slug text not null,
  status text not null default 'available'::text,
  published boolean not null default false,
  published_at timestamptz,
  city text,
  state text,
  neighborhood text,
  rent_amount integer,
  -- App-alignment columns discovered during code audit.
  deposit_amount integer,
  available_date date,
  beds integer,
  baths integer,
  sqft integer,
  description text,
  contact_email text,
  contact_phone text,
  hide_exact_address boolean not null default true,
  address_line1 text,
  address_line2 text,
  postal_code text
);

create unique index if not exists listings_slug_key on public.listings (slug);

create table if not exists public.listing_photos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  listing_id bigint not null,
  owner_id uuid not null,
  image_url text not null,
  sort_order integer not null default 0
);

create table if not exists public.listing_inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  listing_id bigint not null,
  owner_id uuid not null,
  name text not null,
  email text not null,
  phone text,
  message text,
  status text not null default 'new'::text
);

create table if not exists public.listing_leads (
  id bigint generated by default as identity primary key,
  listing_id bigint not null,
  name text not null,
  email text not null,
  phone text,
  message text,
  status text not null default 'new'::text,
  created_at timestamptz not null default now()
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text not null,
  file_url text not null,
  storage_path text not null,
  property_id bigint,
  tenant_id bigint
);

create table if not exists public.esign_purchases (
  id uuid primary key default gen_random_uuid(),
  landlord_user_id uuid not null,
  signatures integer not null,
  amount integer not null,
  paid_at timestamptz not null default now(),
  stripe_payment_intent_id text,
  stripe_checkout_session_id text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.esign_envelopes (
  id bigint generated by default as identity primary key,
  landlord_user_id uuid not null,
  landlord_email text not null,
  document_title text not null,
  signer_name text not null,
  signer_email text not null,
  stripe_session_id text,
  stripe_payment_intent_id text,
  amount_cents integer not null,
  status text not null default 'checkout_created'::text,
  esign_provider text,
  esign_request_id text,
  esign_signing_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.expenses (
  id uuid primary key default gen_random_uuid(),
  landlord_id bigint,
  property_id bigint,
  amount numeric not null,
  category text,
  description text,
  expense_date date not null default now(),
  created_at timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- Foreign keys from provided relationship snapshot
-- ---------------------------------------------------------------------------

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'documents_property_id_fkey') then
    alter table public.documents add constraint documents_property_id_fkey
      foreign key (property_id) references public.properties(id) on delete set null;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'documents_tenant_id_fkey') then
    alter table public.documents add constraint documents_tenant_id_fkey
      foreign key (tenant_id) references public.tenants(id) on delete set null;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'maintenance_requests_tenant_id_fkey') then
    alter table public.maintenance_requests add constraint maintenance_requests_tenant_id_fkey
      foreign key (tenant_id) references public.tenants(id) on delete set null;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'maintenance_requests_property_id_fkey') then
    alter table public.maintenance_requests add constraint maintenance_requests_property_id_fkey
      foreign key (property_id) references public.properties(id) on delete set null;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'messages_landlord_id_fkey') then
    alter table public.messages add constraint messages_landlord_id_fkey
      foreign key (landlord_id) references public.landlords(id) on delete cascade;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'messages_tenant_id_fkey') then
    alter table public.messages add constraint messages_tenant_id_fkey
      foreign key (tenant_id) references public.tenants(id) on delete cascade;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'listing_photos_listing_id_fkey') then
    alter table public.listing_photos add constraint listing_photos_listing_id_fkey
      foreign key (listing_id) references public.listings(id) on delete cascade;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'listing_inquiries_listing_id_fkey') then
    alter table public.listing_inquiries add constraint listing_inquiries_listing_id_fkey
      foreign key (listing_id) references public.listings(id) on delete cascade;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'expenses_landlord_id_fkey') then
    alter table public.expenses add constraint expenses_landlord_id_fkey
      foreign key (landlord_id) references public.landlords(id) on delete set null;
  end if;

  if not exists (select 1 from pg_constraint where conname = 'expenses_property_id_fkey') then
    alter table public.expenses add constraint expenses_property_id_fkey
      foreign key (property_id) references public.properties(id) on delete set null;
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- RLS and policy baseline (from provided policy snapshot; key tables)
-- ---------------------------------------------------------------------------

alter table if exists public.landlords enable row level security;
alter table if exists public.landlord_team_members enable row level security;
alter table if exists public.listings enable row level security;
alter table if exists public.listing_photos enable row level security;
alter table if exists public.listing_inquiries enable row level security;
alter table if exists public.listing_leads enable row level security;
alter table if exists public.documents enable row level security;
alter table if exists public.maintenance_requests enable row level security;
alter table if exists public.messages enable row level security;
alter table if exists public.properties enable row level security;
alter table if exists public.tenants enable row level security;
alter table if exists public.payments enable row level security;

-- listings
drop policy if exists listings_public_read_published on public.listings;
create policy listings_public_read_published
  on public.listings for select
  to anon, authenticated
  using (published = true);

drop policy if exists listings_owner_select on public.listings;
create policy listings_owner_select
  on public.listings for select
  to authenticated
  using (owner_id = auth.uid());

drop policy if exists listings_owner_insert on public.listings;
create policy listings_owner_insert
  on public.listings for insert
  to authenticated
  with check (owner_id = auth.uid());

drop policy if exists listings_owner_update on public.listings;
create policy listings_owner_update
  on public.listings for update
  to authenticated
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

drop policy if exists listings_owner_delete on public.listings;
create policy listings_owner_delete
  on public.listings for delete
  to authenticated
  using (owner_id = auth.uid());

-- listing photos
drop policy if exists listing_photos_public_read_if_published on public.listing_photos;
create policy listing_photos_public_read_if_published
  on public.listing_photos for select
  to anon, authenticated
  using (exists (select 1 from public.listings l where l.id = listing_photos.listing_id and l.published = true));

drop policy if exists listing_photos_owner_select on public.listing_photos;
create policy listing_photos_owner_select
  on public.listing_photos for select
  to authenticated
  using (owner_id = auth.uid());

drop policy if exists listing_photos_owner_insert on public.listing_photos;
create policy listing_photos_owner_insert
  on public.listing_photos for insert
  to authenticated
  with check (owner_id = auth.uid());

drop policy if exists listing_photos_owner_update on public.listing_photos;
create policy listing_photos_owner_update
  on public.listing_photos for update
  to authenticated
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

drop policy if exists listing_photos_owner_delete on public.listing_photos;
create policy listing_photos_owner_delete
  on public.listing_photos for delete
  to authenticated
  using (owner_id = auth.uid());

-- listing inquiries/leads
drop policy if exists listing_inquiries_public_insert_published_only on public.listing_inquiries;
create policy listing_inquiries_public_insert_published_only
  on public.listing_inquiries for insert
  to anon, authenticated
  with check (exists (select 1 from public.listings l where l.id = listing_inquiries.listing_id and l.published = true));

drop policy if exists listing_inquiries_owner_select on public.listing_inquiries;
create policy listing_inquiries_owner_select
  on public.listing_inquiries for select
  to authenticated
  using (owner_id = auth.uid());

drop policy if exists listing_inquiries_owner_update on public.listing_inquiries;
create policy listing_inquiries_owner_update
  on public.listing_inquiries for update
  to authenticated
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

drop policy if exists listing_inquiries_owner_delete on public.listing_inquiries;
create policy listing_inquiries_owner_delete
  on public.listing_inquiries for delete
  to authenticated
  using (owner_id = auth.uid());

drop policy if exists listing_leads_auth_insert on public.listing_leads;
create policy listing_leads_auth_insert
  on public.listing_leads for insert
  to authenticated
  with check (true);

drop policy if exists listing_leads_anon_insert on public.listing_leads;
create policy listing_leads_anon_insert
  on public.listing_leads for insert
  to anon
  with check (true);

-- landlords
drop policy if exists landlord_all_own_row on public.landlords;
create policy landlord_all_own_row
  on public.landlords for all
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists landlord_insert_own_row on public.landlords;
create policy landlord_insert_own_row
  on public.landlords for insert
  to authenticated
  with check (email = (auth.jwt() ->> 'email'::text));

-- landlord team members
drop policy if exists landlord_team_full_access on public.landlord_team_members;
create policy landlord_team_full_access
  on public.landlord_team_members for all
  to authenticated
  using (owner_user_id = auth.uid())
  with check (owner_user_id = auth.uid());

drop policy if exists landlord_team_accept_invite on public.landlord_team_members;
create policy landlord_team_accept_invite
  on public.landlord_team_members for update
  to authenticated
  using (invite_email = auth.email())
  with check ((invite_email = auth.email()) and (member_user_id = auth.uid()));

-- documents / expenses shortcuts for owner rows
drop policy if exists landlord_can_read_documents on public.documents;
create policy landlord_can_read_documents
  on public.documents for select
  to authenticated
  using (property_id in (select p.id from public.properties p where p.owner_id = auth.uid()));

drop policy if exists landlord_documents_crud on public.documents;
create policy landlord_documents_crud
  on public.documents for all
  to authenticated
  using (property_id in (select p.id from public.properties p where p.owner_id = auth.uid()))
  with check (property_id in (select p.id from public.properties p where p.owner_id = auth.uid()));

drop policy if exists expenses_owner_select on public.expenses;
create policy expenses_owner_select
  on public.expenses for select
  to authenticated
  using (landlord_id in (select l.id from public.landlords l where l.user_id = auth.uid()));

drop policy if exists expenses_owner_crud on public.expenses;
create policy expenses_owner_crud
  on public.expenses for all
  to authenticated
  using (landlord_id in (select l.id from public.landlords l where l.user_id = auth.uid()))
  with check (landlord_id in (select l.id from public.landlords l where l.user_id = auth.uid()));
